"""Add dob & gender column to Patients

Revision ID: 756344d27b74
Revises: 2da008b73bc1
Create Date: 2025-06-05 00:27:14.068266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756344d27b74'
down_revision: Union[str, None] = '2da008b73bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('gender', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'gender')
    op.drop_column('patients', 'dob')
    # ### end Alembic commands ###
